/**
 * MarkdownRenderer Component
 * 
 * Renders remote Markdown content fetched from API.
 * Features:
 * - GitHub Flavored Markdown support (remark-gfm)
 * - GitHub Alerts / Callouts (remark-github-blockquote-alert)
 * - Code syntax highlighting (rehype-highlight)
 * - Math formula rendering (remark-math + rehype-katex)
 * - [TOC] / Table of Contents generation (remark-toc)
 * - Heading anchor links with smooth scroll (rehype-slug)
 * - Internal article link routing (next/link)
 * - External links open in new tab
 * - Image path transformation (relative -> /api/v1/assets/ paths)
 * - Dracula Spectrum styling (aligned with article view prototype HTML)
 * 
 * Supported alert types:
 *   > [!NOTE]     -> informational callout
 *   > [!TIP]      -> helpful suggestion
 *   > [!IMPORTANT] -> critical information
 *   > [!WARNING]  -> cautionary advice
 *   > [!CAUTION]  -> potential danger
 * 
 * Usage:
 * <MarkdownRenderer content={markdownContent} basePath="tech/blog" />
 */

/* eslint-disable @next/next/no-img-element */

"use client";

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeHighlight from 'rehype-highlight';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import { remarkAlert } from 'remark-github-blockquote-alert';
import rehypeSlug from 'rehype-slug';
import remarkToc from 'remark-toc';
import Link from 'next/link';
import 'katex/dist/katex.min.css';
import { isValidElement, Children } from 'react';
import { encodePathForUrl } from '@/lib/utils/path';
import type { ComponentPropsWithoutRef, ReactElement, ReactNode } from 'react';

interface MarkdownRendererProps {
  content: string;
  basePath?: string;  // Article directory path for image transformation
}

/**
 * Transform Markdown image paths to API resource paths
 * 
 * Rules (RESTful v1 API):
 * 1. External links (http/https): keep as-is
 * 2. Absolute paths (/...): convert to /api/v1/assets{src}
 * 3. Relative paths starting with .assets: strip .assets layer for cleaner API path
 *    e.g., "./.assets/images/photo.png" + basePath="guides" -> "/api/v1/assets/guides/images/photo.png"
 * 4. Other relative paths: convert to /api/v1/assets/{basePath}/{imagePath}
 */
function transformImagePath(src: string, basePath?: string): string {
  // External links: keep as-is
  if (src.startsWith('http://') || src.startsWith('https://')) {
    return src;
  }
  
  // Absolute paths: add /api/v1/assets prefix
  if (src.startsWith('/')) {
    return `/api/v1/assets${src}`;
  }
  
  // Normalize relative path
  let normalizedPath = src;
  if (normalizedPath.startsWith('./')) {
    normalizedPath = normalizedPath.slice(2);
  }
  
  // Special handling for .assets directory: strip the .assets layer
  // This simplifies API path from /api/v1/assets/guides/.assets/images/photo.png
  // to /api/v1/assets/guides/images/photo.png
  if (normalizedPath.startsWith('.assets/')) {
    normalizedPath = normalizedPath.slice(8); // Remove ".assets/" prefix
  }
  
  const fullPath = basePath 
    ? `${basePath}/${normalizedPath}` 
    : normalizedPath;
  
  return `/api/v1/assets/${fullPath}`;
}

function extractLanguageLabel(className: string): string {
  const langMatch = /language-([A-Za-z0-9_+-]+)/.exec(className);
  if (!langMatch) {
    return '';
  }

  const language = langMatch[1].toLowerCase();
  const aliases: Record<string, string> = {
    js: 'JavaScript',
    ts: 'TypeScript',
    tsx: 'TSX',
    jsx: 'JSX',
    sh: 'Shell',
    bash: 'Bash',
    zsh: 'Zsh',
    yml: 'YAML',
    md: 'Markdown',
    plaintext: 'Plain Text',
    text: 'Plain Text',
    golang: 'Go',
    csharp: 'C#',
    cpp: 'C++',
  };

  return aliases[language] ?? language.toUpperCase();
}

/**
 * Check if a list is a Table of Contents generated by remark-toc.
 * Heuristic: all direct children are <li> elements containing an <a> with href starting with '#'.
 */
function isTocList(children: ReactNode): boolean {
  const items = Children.toArray(children);
  if (items.length < 2) return false;
  return items.every(child => {
    if (!isValidElement(child)) return false;
    const el = child as React.ReactElement<{ children?: ReactNode }>;
    const liChildren = Children.toArray(el.props.children);
    return liChildren.some(grandchild => {
      if (!isValidElement(grandchild)) return false;
      const gc = grandchild as React.ReactElement<{ href?: string }>;
      return gc.type === 'a' && typeof gc.props.href === 'string' && gc.props.href.startsWith('#');
    });
  });
}

/**
 * Convert heading children to a string slug.
 * Used as fallback when rehype-slug doesn't generate an id.
 */
function childrenToText(children: ReactNode): string {
  let text = '';
  Children.forEach(children, child => {
    if (typeof child === 'string') {
      text += child;
    } else if (isValidElement(child)) {
      const el = child as React.ReactElement<{ children?: ReactNode }>;
      text += childrenToText(el.props.children);
    }
  });
  return text;
}

/**
 * Generate a URL-safe slug from heading text.
 * Used as fallback slug when rehype-slug id is unavailable.
 */
function generateSlug(children: ReactNode): string {
  const text = childrenToText(children);
  return text
    .toLowerCase()
    .replace(/[^\w\u4e00-\u9fff]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'heading';
}

/**
 * Handle anchor link click: smooth scroll + URL hash update.
 */
function handleAnchorClick(e: React.MouseEvent, href: string) {
  e.preventDefault();
  const id = href.slice(1);
  const target = document.getElementById(id);
  if (target) {
    target.scrollIntoView({ behavior: 'smooth' });
    window.history.pushState(null, '', href);
  }
}

export function MarkdownRenderer({ content, basePath }: MarkdownRendererProps) {
  return (
    <div className="markdown-body">
      <ReactMarkdown
        remarkPlugins={[
          remarkGfm,
          remarkMath,
          remarkAlert,
          [remarkToc, { heading: "目录|contents" }],
        ]}
        rehypePlugins={[
          rehypeSlug,
          rehypeHighlight,
          rehypeKatex,
        ]}
        components={{
          // ----- Headings with anchor links -----
          h1: ({ children, id }) => {
            const slug = id || generateSlug(children);
            return (
              <h1 id={slug}
                  className="group font-headline text-4xl md:text-5xl font-bold leading-none
                             text-on-surface tracking-tighter mb-8 mt-12 first:mt-0">
                <a href={`#${slug}`}
                   onClick={(e) => handleAnchorClick(e, `#${slug}`)}
                   className="anchor-link opacity-0 group-hover:opacity-100 focus-visible:opacity-100
                              mr-2 text-secondary no-underline select-none
                              transition-opacity duration-150"
                   aria-hidden="true">#</a>
                {children}
              </h1>
            );
          },

          h2: ({ children, id }) => {
            const slug = id || generateSlug(children);
            return (
              <h2 id={slug}
                  className="group font-headline text-3xl font-bold text-secondary-fixed-dim">
                <a href={`#${slug}`}
                   onClick={(e) => handleAnchorClick(e, `#${slug}`)}
                   className="anchor-link opacity-0 group-hover:opacity-100 focus-visible:opacity-100
                              mr-2 text-secondary no-underline select-none
                              transition-opacity duration-150"
                   aria-hidden="true">#</a>
                {children}
              </h2>
            );
          },

          h3: ({ children, id }) => {
            const slug = id || generateSlug(children);
            return (
              <h3 id={slug}
                  className="group font-headline text-2xl font-bold text-secondary-fixed mb-4">
                <a href={`#${slug}`}
                   onClick={(e) => handleAnchorClick(e, `#${slug}`)}
                   className="anchor-link opacity-0 group-hover:opacity-100 focus-visible:opacity-100
                              mr-2 text-secondary no-underline select-none
                              transition-opacity duration-150"
                   aria-hidden="true">#</a>
                {children}
              </h3>
            );
          },

          h4: ({ children, id }) => {
            const slug = id || generateSlug(children);
            return (
              <h4 id={slug}
                  className="group font-headline text-xl font-bold text-on-surface mb-4">
                <a href={`#${slug}`}
                   onClick={(e) => handleAnchorClick(e, `#${slug}`)}
                   className="anchor-link opacity-0 group-hover:opacity-100 focus-visible:opacity-100
                              mr-2 text-secondary no-underline select-none
                              transition-opacity duration-150"
                   aria-hidden="true">#</a>
                {children}
              </h4>
            );
          },

          h5: ({ children, id }) => {
            const slug = id || generateSlug(children);
            return (
              <h5 id={slug}
                  className="group font-headline text-lg font-bold text-on-surface mb-3">
                <a href={`#${slug}`}
                   onClick={(e) => handleAnchorClick(e, `#${slug}`)}
                   className="anchor-link opacity-0 group-hover:opacity-100 focus-visible:opacity-100
                              mr-2 text-secondary no-underline select-none
                              transition-opacity duration-150"
                   aria-hidden="true">#</a>
                {children}
              </h5>
            );
          },

          h6: ({ children, id }) => {
            const slug = id || generateSlug(children);
            return (
              <h6 id={slug}
                  className="group font-headline text-base font-bold text-on-surface mb-2">
                <a href={`#${slug}`}
                   onClick={(e) => handleAnchorClick(e, `#${slug}`)}
                   className="anchor-link opacity-0 group-hover:opacity-100 focus-visible:opacity-100
                              mr-2 text-secondary no-underline select-none
                              transition-opacity duration-150"
                   aria-hidden="true">#</a>
                {children}
              </h6>
            );
          },

          // ----- Body text -----
          p: ({ children }) => (
            <p className="mb-4">
              {children}
            </p>
          ),

          // ----- Code blocks -----
          pre: ({ children }) => {
            const childCode = (Array.isArray(children) ? children[0] : children) as ReactElement<ComponentPropsWithoutRef<'code'>> | ReactNode;
            const codeProps = isValidElement<ComponentPropsWithoutRef<'code'>>(childCode)
              ? childCode.props
              : undefined;
            const className = codeProps?.className || '';
            const language = extractLanguageLabel(className);

            return (
              <section className="markdown-code-block">
                {language && (
                  <div className="markdown-code-block__label">
                    {language}
                  </div>
                )}
                <pre className="markdown-code-block__pre">{children}</pre>
              </section>
            );
          },

          code: ({ className, children, ...props }) => {
            const textContent = typeof children === 'string'
              ? children
              : Array.isArray(children)
                ? children.join('')
                : '';
            const isMultilineCodeBlock = !className && textContent.includes('\n');

            if (!className && !isMultilineCodeBlock) {
              return (
                <code className="markdown-inline-code">
                  {children}
                </code>
              );
            }

            return (
              <code className={className} {...props}>
                {children}
              </code>
            );
          },

          // ----- Blockquotes -----
          blockquote: ({ children }) => (
            <blockquote className="markdown-blockquote">
              <div className="markdown-blockquote__content">{children}</div>
            </blockquote>
          ),

          // ----- Lists (with TOC detection) -----
          ul: ({ children }) => {
            const tocList = isTocList(children);
            return (
              <ul className={
                tocList
                  ? 'markdown-toc'
                  : 'markdown-list markdown-list--unordered'
              }>
                {children}
              </ul>
            );
          },

          ol: ({ children }) => (
            <ol className="markdown-list markdown-list--ordered">
              {children}
            </ol>
          ),

          li: ({ children }) => (
            <li className="markdown-list__item">
              <div className="markdown-list__content">
                {children}
              </div>
            </li>
          ),

          // ----- Tables -----
          table: ({ children }) => (
            <div className="markdown-table-shell my-10">
              <div className="markdown-table-scroll">
                <table className="markdown-table">
                  {children}
                </table>
              </div>
            </div>
          ),

          thead: ({ children }) => (
            <thead className="markdown-table-head">
              {children}
            </thead>
          ),

          tbody: ({ children }) => (
            <tbody className="markdown-table-body">
              {children}
            </tbody>
          ),

          tr: ({ children }) => (
            <tr className="markdown-table-row">
              {children}
            </tr>
          ),

          th: ({ children }) => (
            <th className="markdown-table-heading">
              {children}
            </th>
          ),

          td: ({ children }) => (
            <td className="markdown-table-cell">
              {children}
            </td>
          ),

          // ----- Links (3 routing modes) -----
          a: ({ href, children }) => {
            // 1. External links -> new tab
            if (href?.startsWith('http')) {
              return (
                <a href={href} target="_blank" rel="noopener noreferrer"
                   className="text-primary hover:text-secondary transition-colors underline">
                  {children}
                </a>
              );
            }

            // 2. Anchor links (including TOC links) -> smooth scroll
            if (href?.startsWith('#')) {
              return (
                <a href={href}
                   onClick={(e) => handleAnchorClick(e, href)}
                   className="text-primary hover:text-secondary transition-colors no-underline hover:underline cursor-pointer">
                  {children}
                </a>
              );
            }

            // 3. Internal article links -> SPA navigation via next/link
            let articlePath = href || '';
            // Strip .md extension
            articlePath = articlePath.replace(/\.md$/i, '');
            // Strip leading ./ or ../
            articlePath = articlePath.replace(/^\.\.?\//, '');
            const targetPath = `/article/${encodePathForUrl(articlePath)}`;

            return (
              <Link href={targetPath}
                    className="text-primary hover:text-secondary transition-colors underline">
                {children}
              </Link>
            );
          },

          // ----- Images -----
          img: ({ src, alt, ...props }) => {
            if (!src) return null;
            const srcString = typeof src === 'string' ? src : '';
            const transformedSrc = transformImagePath(srcString, basePath);
            return (
              <img 
                src={transformedSrc} 
                alt={alt} 
                loading="lazy"
                className="max-w-full h-auto"
                {...props} 
              />
            );
          },

          // ----- Horizontal rule -----
          hr: () => (
            <hr className="border-t border-surface-container my-8" />
          ),

          // ----- Inline formatting -----
          strong: ({ children }) => (
            <strong className="text-primary font-bold">
              {children}
            </strong>
          ),

          em: ({ children }) => (
            <em className="text-outline italic">
              {children}
            </em>
          ),
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}
